# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: benfreke.menumanager::lang.menu.name

# Model Form Field configuration
form: ~/plugins/benfreke/menumanager/models/menu/fields.yaml

# Model Class name
modelClass: BenFreke\MenuManager\Models\Menu

# Default redirect location
defaultRedirect: benfreke/menumanager/menus

# Create page
create:
    title: benfreke.menumanager::lang.form.create
    redirect: benfreke/menumanager/menus/update/:id
    redirectClose: benfreke/menumanager/menus
    flash-save: benfreke.menumanager::lang.form.flashcreate

# Update page
update:
    title: benfreke.menumanager::lang.form.update
    redirect: benfreke/menumanager/menus
    redirectClose: benfreke/menumanager/menus
    flash-save: benfreke.menumanager::lang.form.flashupdate
    flash-delete: benfreke.menumanager::lang.form.flashdelete

# Preview page
preview:
    title: benfreke.menumanager::lang.form.preview

